# Generated by Django 6.0.4 on 2026-04-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drrmo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentreport',
            name='recommendations',
            field=models.TextField(blank=True),
        ),
    ]
