# Generated by Django 6.0.4 on 2026-04-10 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drrmo', '0003_place_latitude_place_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloodRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('barangay', models.CharField(blank=True, max_length=200)),
                ('location_description', models.CharField(blank=True, max_length=255)),
                ('severity', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('affected_households', models.PositiveIntegerField(blank=True, null=True)),
                ('impact_details', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flood_records', to='drrmo.place')),
            ],
            options={
                'ordering': ['-event_date', '-created_at'],
            },
        ),
    ]
