# Generated by Django 6.0.4 on 2026-04-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drrmo', '0004_floodrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(default='Silay City', max_length=255)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField()),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
    ]
