# Generated by Django 6.0.4 on 2026-04-10 14:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drrmo', '0005_weatherdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentreport',
            name='risk_level',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer_name', models.CharField(max_length=200)),
                ('requestor_name', models.CharField(max_length=200)),
                ('business_name', models.CharField(max_length=255)),
                ('project_name', models.CharField(blank=True, max_length=255)),
                ('issued_date', models.DateField(default=datetime.date.today)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='drrmo.place')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='drrmo.assessmentreport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
